sudo: required

services:
  - docker

env:
  global:
    # DOCKER_USERNAME
    - secure: "gdJJKoo3itgg8P4I/BvqT5PxWUD2iTGEOM567JJ4zy0N2EaBPgMrR2Cfc2sW2dJpGwL2V/vhTUZ8O4J7DXdlgc+kAB68seTCEWk8NKv2kQymconlpmaCbBNnLYpi8sE8aIgXBcRdexDoZ+Oi4Tcen+esF0FPlNRX9Y9XzbpqJq3FlsEUlmVCUP9duwFIYxCGKGvGsJdpuQHt1PEoZJvYJCYruMYUxJeERzbs8Ge6Pu3i2erTQBKT5+i8yiAeMpV6DELkS5c2vl5P/nONmM6BdvyUCpvnoF6IGoptN12PeLghQ2wm7Yr2xF//7esdx4yUXaBSKpKhFNNGaBB5o+7SeAsCkmclZs72Ne9Ny2ubyeB14AH11w0Jqic4QbwYIHUBfFn3w//mt6sCNKfNrB0q6aPJANiXm/CShSz5Blz4JFHZxKnyJypMnuKGFuWKDLKWSBYS6kLYcDx5bbcQaj4paSxzUNnvUwATT/4V+3sVM1UE6TBlm3AB+v/III+3GJFSOJPU78H02/+tBScRZctjHVCHtTrSonXFa3cVdSo3iSHaSYQzznu56e6ASzNr4MZfMMOdaf7mqLScJwxEAs73b8xzELOat52TC7U09SdRJXtGq8Thnqax4LaLame7qcrsEdPAJM7Q8fiemC8daFvoZh3VbEkOsZqhHb3AEg7mmas="
    # DOCKER_PASSWORD
    - secure: "lgDK95977Qd776J5qV8ROp21f1oRMzLzdCMHiLjI7GWp9YmWyYOY7/7OPQhskSfsnE3JaUO+PJXf65h0c85dVxO/VzxRxIiAGMm+9Ac676D1sJc1DCLedNYtk8jLq/pxcOLo2uSMQTe+yOrTEO9dxJtDEvX50drXsmredpMwm/2UNatLUkfI/0TqYx8vOsp/m+oN3DQO3iFfaKG1BEDRT19p+zMZk5NV6maHmzKRYZwhazn2BxnQGKcxCOynEYYRoxsllunUxBxcXv+fzxFxYjHWaIfkETzAr2IWMbJfpy6N+xsz2GhIImM6ixFBKsl/6syNGRQkvH4OVwyk9RN1j0RLENXPl7kuTw+kA3aejNZKmArC52fEEgStlhylaf+MmkNBbuGoISoBAeXut6Hnp5RoE0H7ykUpANCZqW1RnC9rQR0XPtW0iaBvbfJ7/iKDib2w294R8nD7zDiMRH75kPN5PbADYUmSzuZ9hAbypJ6sEAThmc9JdYQwiVGQ+U6GplEsHMH5KQYJAlVx1UEeEYTlfPM84GAlCDy5meXL1TpgbFlY3fKf/3PLVDMEGjXsWRxmXUSvEnA7S5BVtxcpspeGhrePOBo5pw1eNSHmUoVZUoMVG6qBK19CVsm/OtywZ9nglXBHcpFbLEtqaH7heCwIEFqy9OXJMkXLGOs+ubg="
    - DOCKERFILE=$'
      FROM smashwilson/lets-nginx\n
      COPY /templates /templates'

before_install:
  - echo "$DOCKERFILE" > Dockerfile
  - echo "$(cat Dockerfile)"
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

script:
  - docker build -t saintech/dev-microstack-nginx .
  - docker push saintech/dev-microstack-nginx
