sudo: required

services:
  - docker

env:
  global:
    - DOCKERFILE=$'
      FROM smashwilson/lets-nginx\n
      COPY /nginx /nginx'

before_install:
  - echo "$DOCKERFILE" > Dockerfile
  - echo "$(cat Dockerfile)"
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

script:
  - docker build -t saintech/dev-microstack-nginx .
  - docker push saintech/dev-microstack-nginx
