sudo: required

services:
  - docker

env:
  # DOCKER_USERNAME
  - secure: "YGQZRYRnWlF27W5tgEbBr1qjR33CdT+h05rrEDK72gh+nmnywgi0oYCZnZ2uQpCBGr1eNLCTkBS0zYvtWu5C3PVaXOLTiQDdiq0wJzJPiCJXUyn3mOIXSyjGNfxF4GNaV80Md0imsLZzLy+/J7CuhY9s3UyvLaevnFSlRA0C9OpbBEb8Xl3xYNRKKLoT8MiktDR6wKFI480fvYyWMagHVy44RXi1QLcbOA3JitxYiniDf/FwGWAbBf5i29SqfuFlOkseR7B1KgYGeGL1qay7tkWs1wzYWezIl+nPgd66lpouQ5hIIDNFPvtUH+G53ywbzxoHrMCBkAqZRowbSR2mMqPmzZOXAdi5XI6MHrRdqH6I2mdXVg0F8lXoJy7TV/PXLn0deUc14cgiQpXRq2pLCFB6dkWRiyxhuvrRIamXlXBfd3+pzIcx9v3/aZGB1Avu9sIAuZjvGuSiOa3RjlZaF6PUazV3Nbok4wshfGCsEVSr3l+DTBw/KwncEa99zVotuJ6YAj9FFJ4IWQ6ph6p3I5uom+32QVAEWa+fTM9tDX4xsZ0MLWumN3+w70WVmnkxJMT8Y/SY915IbDXcSP0rGGaPmJbv5iMaxY8y62kaIHDRL0n2QrCATqGURk2ZPxsINe/YUaaIIUxe7JBzPkmuf3OOOSxe2BBmF3ZN9X/UA9c="
  # DOCKER_PASSWORD
  - secure: "lgDK95977Qd776J5qV8ROp21f1oRMzLzdCMHiLjI7GWp9YmWyYOY7/7OPQhskSfsnE3JaUO+PJXf65h0c85dVxO/VzxRxIiAGMm+9Ac676D1sJc1DCLedNYtk8jLq/pxcOLo2uSMQTe+yOrTEO9dxJtDEvX50drXsmredpMwm/2UNatLUkfI/0TqYx8vOsp/m+oN3DQO3iFfaKG1BEDRT19p+zMZk5NV6maHmzKRYZwhazn2BxnQGKcxCOynEYYRoxsllunUxBxcXv+fzxFxYjHWaIfkETzAr2IWMbJfpy6N+xsz2GhIImM6ixFBKsl/6syNGRQkvH4OVwyk9RN1j0RLENXPl7kuTw+kA3aejNZKmArC52fEEgStlhylaf+MmkNBbuGoISoBAeXut6Hnp5RoE0H7ykUpANCZqW1RnC9rQR0XPtW0iaBvbfJ7/iKDib2w294R8nD7zDiMRH75kPN5PbADYUmSzuZ9hAbypJ6sEAThmc9JdYQwiVGQ+U6GplEsHMH5KQYJAlVx1UEeEYTlfPM84GAlCDy5meXL1TpgbFlY3fKf/3PLVDMEGjXsWRxmXUSvEnA7S5BVtxcpspeGhrePOBo5pw1eNSHmUoVZUoMVG6qBK19CVsm/OtywZ9nglXBHcpFbLEtqaH7heCwIEFqy9OXJMkXLGOs+ubg="
  - DOCKERFILE=$'
    FROM smashwilson/lets-nginx\n
    COPY /templates /templates'

before_install:
  - echo "$DOCKERFILE" > Dockerfile
  - echo "$(cat Dockerfile)"
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

script:
  - docker build -t saintech/dev-microstack-nginx .
  - docker push saintech/dev-microstack-nginx
