sudo: required

services:
  - docker

env:
  - DOCKERFILE = $'
    FROM smashwilson/lets-nginx\n
    COPY /templates /templates'

before_install:
  - echo "$DOCKERFILE" > Dockerfile
  - echo "$(cat Dockerfile)"
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

script:
  - docker build -t saintech/dev-microstack-nginx .
  - docker push saintech/dev-microstack-nginx
